/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#5c647a",
        "primary-fixed-dim": "#4edea3",
        "on-primary-container": "#eee3e3",
        "primary": "#006c49",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#006c49",
        "secondary-fixed": "#dae2fd",
        "secondary": "#565e74",
        "surface": "#f7f9fb",
        "on-primary-fixed": "#002113",
        "surface-dim": "#d8dadc",
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
        "on-secondary-fixed": "#131b2e",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#6ffbbe",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-container": "#780021",
        "tertiary-container": "#ff7886",
        "on-primary-fixed-variant": "#005236",
        "on-error": "#ffffff",
        "inverse-surface": "#2d3133",
        "on-secondary": "#ffffff",
        "inverse-primary": "#4edea3",
        "tertiary-fixed": "#ffdadb",
        "on-tertiary-fixed-variant": "#92002a",
        "outline-variant": "#bbcabf",
        "secondary-fixed-dim": "#bec6e0",
        "tertiary-fixed-dim": "#ffb2b7",
        "on-tertiary-fixed": "#40000d",
        "tertiary": "#bc0b3b",
        "surface-container-low": "#f2f4f6",
        "surface-variant": "#e0e3e5",
        "primary-container": "#10b981",
        "on-surface-variant": "#3c4a42",
        "error-container": "#ffdad6",
        "secondary-container": "#dae2fd",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "outline": "#6c7a71",
        "on-primary": "#ffffff",
        "surface-container": "#eceef0",
        "on-error-container": "#93000a",
        "background": "#f7f9fb",
        "error": "#ba1a1a",
        
        // Dark Mode Explicit Map
        "dark-surface": "#060e20",
        "dark-surface-variant": "#192540",
        "dark-primary": "#69f6b8",
        "dark-secondary": "#ff6f7e",
        "dark-tertiary": "#47c4ff",
        "dark-on-surface": "#dee5ff",
        "dark-on-surface-variant": "#a3aac4",
        "dark-surface-container": "#0f1930",
        "dark-surface-container-high": "#141f38",
        "dark-outline-variant": "#40485d",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
